### ISSUE TITLE
Map, Filter, and Reduce

### ISSUE THREAD

**Issue by jacobp100** [terkelg/zet#1]
I’ve always thought it would be quite useful to have these array methods. Map and filter would return sets.

**Comment by terkelg** [comment]
Good idea! I'm a bit busy right now, but I'm open to PRs. But yeah, could be nice to have for sure.

**Comment by terkelg** [comment]
Added a reduce function thanks to @199911 👍It's in the latest release. 
Let me know @199911 if you're interested in implementing map and reduce too

**Comment by terkelg** [comment]
Implemented in #5
